/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface WpCommentmeta {
  commentId: Generated<number>;
  metaId: Generated<number>;
  metaKey: string | null;
  metaValue: string | null;
}

export interface WpComment {
  commentAgent: Generated<string>;
  commentApproved: Generated<string>;
  commentAuthor: string;
  commentAuthorEmail: Generated<string>;
  commentAuthorIP: Generated<string>;
  commentAuthorUrl: Generated<string>;
  commentContent: string;
  commentDate: Generated<Date>;
  commentDateGmt: Generated<Date>;
  commentID: Generated<number>;
  commentKarma: Generated<number>;
  commentParent: Generated<number>;
  commentPostID: Generated<number>;
  commentType: Generated<string>;
  userId: Generated<number>;
}

export interface WpLink {
  linkDescription: Generated<string>;
  linkId: Generated<number>;
  linkImage: Generated<string>;
  linkName: Generated<string>;
  linkNotes: string;
  linkOwner: Generated<number>;
  linkRating: Generated<number>;
  linkRel: Generated<string>;
  linkRss: Generated<string>;
  linkTarget: Generated<string>;
  linkUpdated: Generated<Date>;
  linkUrl: Generated<string>;
  linkVisible: Generated<string>;
}

export interface WpNextpressPostmeta {
  metaId: Generated<number>;
  metaKey: string | null;
  metaValue: string | null;
  objectId: Generated<number>;
}

export interface WpNextpressTermmeta {
  metaId: Generated<number>;
  metaKey: string | null;
  metaValue: string | null;
  objectId: Generated<number>;
}

export interface WpOption {
  autoload: Generated<string>;
  optionId: Generated<number>;
  optionName: Generated<string>;
  optionValue: string;
}

export interface WpPostmeta {
  metaId: Generated<number>;
  metaKey: string | null;
  metaValue: string | null;
  postId: Generated<number>;
}

export interface WpPost {
  commentCount: Generated<number>;
  commentStatus: Generated<string>;
  guid: Generated<string>;
  ID: Generated<number>;
  menuOrder: Generated<number>;
  pinged: string;
  pingStatus: Generated<string>;
  postAuthor: Generated<number>;
  postContent: string;
  postContentFiltered: string;
  postDate: Generated<Date>;
  postDateGmt: Generated<Date>;
  postExcerpt: string;
  postMimeType: Generated<string>;
  postModified: Generated<Date>;
  postModifiedGmt: Generated<Date>;
  postName: Generated<string>;
  postParent: Generated<number>;
  postPassword: Generated<string>;
  postStatus: Generated<string>;
  postTitle: string;
  postType: Generated<string>;
  toPing: string;
}

export interface WpTermmeta {
  metaId: Generated<number>;
  metaKey: string | null;
  metaValue: string | null;
  termId: Generated<number>;
}

export interface WpTermRelationship {
  objectId: Generated<number>;
  termOrder: Generated<number>;
  termTaxonomyId: Generated<number>;
}

export interface WpTerm {
  name: Generated<string>;
  slug: Generated<string>;
  termGroup: Generated<number>;
  termId: Generated<number>;
}

export interface WpTermTaxonomy {
  count: Generated<number>;
  description: string;
  parent: Generated<number>;
  taxonomy: Generated<string>;
  termId: Generated<number>;
  termTaxonomyId: Generated<number>;
}

export interface WpUsermeta {
  metaKey: string | null;
  metaValue: string | null;
  umetaId: Generated<number>;
  userId: Generated<number>;
}

export interface WpUser {
  displayName: Generated<string>;
  ID: Generated<number>;
  userActivationKey: Generated<string>;
  userEmail: Generated<string>;
  userLogin: Generated<string>;
  userNicename: Generated<string>;
  userPass: Generated<string>;
  userRegistered: Generated<Date>;
  userStatus: Generated<number>;
  userUrl: Generated<string>;
}

export interface DB {
  wpCommentmeta: WpCommentmeta;
  wpComments: WpComment;
  wpLinks: WpLink;
  wpNextpressPostmeta: WpNextpressPostmeta;
  wpNextpressTermmeta: WpNextpressTermmeta;
  wpOptions: WpOption;
  wpPostmeta: WpPostmeta;
  wpPosts: WpPost;
  wpTermmeta: WpTermmeta;
  wpTermRelationships: WpTermRelationship;
  wpTerms: WpTerm;
  wpTermTaxonomy: WpTermTaxonomy;
  wpUsermeta: WpUsermeta;
  wpUsers: WpUser;
}
